# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-LijhxNmIC1sY4KEMmHm_8TiH3ELVLI
"""

from flask import Flask, request, jsonify, render_template
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# =========================
# 1. Cargar dataset
# =========================
df = pd.read_csv("base_1.2.csv")

# Eliminar nulos importantes
df = df.dropna(subset=["pregunta", "intencion", "respuesta"])

# =========================
# 2. Variables
# =========================
X = df["pregunta"]
y = df["intencion"]

# =========================
# 3. Vectorización
# =========================
vectorizador = TfidfVectorizer()
X_vectorizado = vectorizador.fit_transform(X)

# =========================
# 4. Entrenamiento
# =========================
modelo = LogisticRegression(max_iter=1000)
modelo.fit(X_vectorizado, y)

# =========================
# 5. Función de respuesta
# =========================
def responder(pregunta_usuario):
    pregunta_vector = vectorizador.transform([pregunta_usuario])
    intencion = modelo.predict(pregunta_vector)[0]

    respuesta = df[df["intencion"] == intencion]["respuesta"].iloc[0]

    return respuesta

# =========================
# 6. Flask app
# =========================
app = Flask(__name__)

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/chat", methods=["POST"])
def chat():
    data = request.get_json()
    pregunta = data.get("pregunta")

    respuesta = responder(pregunta)

    return jsonify({"respuesta": respuesta})

# =========================
# 7. Ejecutar
# =========================
if __name__ == "__main__":
    app.run(debug=True)

